YUI.add('moodle-block_skype_web-skype', function (Y) {
    var ModulenameNAME = 'skpe';
    var token = '';
    var MODULENAME = function () {
        MODULENAME.superclass.constructor.apply(this, arguments);
    };
    Y.extend(MODULENAME, Y.Base, {
        initializer: function (config) {

            var skype_state = '';
            var skype_div = document.getElementById('skype_status');
            var skypeConfig = {
                version: 'SkypeOnlinePreviewApp/1.0.0', // this helps to identify telemetry generated by the samples
                apiKey: 'a42fcebd-5b43-4b89-a065-74450fb91255', // SDK DF
                apiKeyCC: '9c967f6b-a846-4df2-b43d-5167e47d81e1' // SDK+CC DF
            };
        }
    }, {
        NAME: ModulenameNAME,
        ATTRS: {
            aparam: {}
        }
    });
    M.block_skype_web = M.block_skype_web || {};

    M.block_skype_web.init_skype = function (config) {
        return new MODULENAME(config);
    };

}, '@VERSION@', {
    requires: ['base']
});