YUI.add('moodle-block_skype_web-skype', function (Y) {
    var ModulenameNAME = 'skpe';
    var token = '';
    var MODULENAME = function () {
        MODULENAME.superclass.constructor.apply(this, arguments);
    };
    Y.extend(MODULENAME, Y.Base, {
        initializer: function (config) {

            var skype_div = document.getElementById('skype_status');
            var skypeConfig = {
                version: 'SkypeOnlinePreviewApp/1.0.0', // this helps to identify telemetry generated by the samples
                apiKey: 'a42fcebd-5b43-4b89-a065-74450fb91255', // SDK DF
                apiKeyCC: '9c967f6b-a846-4df2-b43d-5167e47d81e1' // SDK+CC DF
            };

            Skype.initialize({apiKey: skypeConfig.apiKey}, function (api) {
                window.skypeWebAppCtor = api.application;
                window.skypeWebApp = new api.application();

                var client = window.skypeWebApp;
                
                window.skypeWebApp.signInManager.state.changed(function (state) {
                    console.log(state);
                    skype_div.innerHTML = state;
                });

                var params =
                {
                    "client_id": "9dd17984-497f-42e1-8304-a3c7f2b5e9c4",
                    "origins": ["https://webdir.online.lync.com/autodiscover/autodiscoverservice.svc/root"],
                    "cors": true,
                    "version": 'SkypeWebMoodle/1.0.0'
                };
                // start signing in

                client.signInManager.signIn(
                    params
                ).then(function () {
                    // when the sign in operation succeeds display the user name
                    console.log('Signed in as ' + client.personsAndGroupsManager.mePerson.displayName());

                }, function (error) {
                    console.log(error || 'Cannot sign in');
                });

            }, function (err) {
                console.log(err);
                alert('Cannot load the Skype SDK.');
            });
        }
    }, {
        NAME: ModulenameNAME,
        ATTRS: {
            aparam: {}
        }
    });
    M.block_skype_web = M.block_skype_web || {};

    M.block_skype_web.init_skype = function (config) {
        return new MODULENAME(config);
    };

}, '@VERSION@', {
    requires: ['base']
});